# Generated by Django 4.2 on 2023-05-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'details_voiture',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='intervalleproduction',
            constraint=models.UniqueConstraint(fields=('debut',), name='unique date de début'),
        ),
        migrations.AddField(
            model_name='detailsvoiture',
            name='id_modele',
            field=models.ForeignKey(db_column='id_modele', on_delete=django.db.models.deletion.CASCADE, to='app.modele'),
        ),
        migrations.AddField(
            model_name='detailsvoiture',
            name='id_voiture',
            field=models.ForeignKey(db_column='id_voiture', on_delete=django.db.models.deletion.CASCADE, to='app.voiture'),
        ),
    ]
